### PR TITLE
adding swagger spec

### PR DESCRIPTION
**Pull request by hardergeorge**
Added swagger

### CODE REVIEW

**Comment by hardergeorge** [comment]
@browtayl No, that was an oversight.

**Comment by hardergeorge** [comment]
@browtayl 
GET /platforms?console=true Would return all of the platforms that are consoles
GET /platforms?console=foo Assuming foo is neither true nor false, I would treat that as an invalid request. The goal of those filters is to quickly allow the user to access all of the consoles or all of the computer platforms.
GET /platforms?console=true&computer=true This would return all of the platforms, a platform is either a console or a computer

**Comment by hardergeorge** [comment]
@browtayl Also, thank you for catching that issue with the array of array of platforms.

**Comment by hardergeorge** [comment]
@browtayl 
1. Yes the fields are mutually exclusive. 
2. I was not considering other possible platform types when I did the design. However, I could imagine this being extended to include some of the example you mention.

**Comment by ghost** [comment]
i [duplicated](https://github.com/osu-mist/videogame-sample-api/pull/2) this pull request against the new default branch `develop` and am closing this one.

**Pull request closed without merging**
